# Generated by Django 3.2.7 on 2021-09-29 00:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('task', models.TextField()),
                ('due_date', models.DateField(auto_now=True)),
                ('task_list', models.CharField(choices=[('Shopping', 'Shopping'), ('Personal', 'Personal'), ('WishList', 'WishList'), ('Work', 'Work'), ('All', 'All List')], max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_list', models.CharField(choices=[('Shopping', 'Shopping'), ('Personal', 'Personal'), ('WishList', 'WishList'), ('Work', 'Work'), ('All', 'All List')], max_length=250)),
            ],
            options={
                'verbose_name': 'Task List',
                'verbose_name_plural': 'Task Lists',
            },
        ),
    ]
