# Generated by Django 3.2.7 on 2021-09-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_list',
            field=models.CharField(choices=[('Shopping', 'Shopping'), ('Personal', 'Personal'), ('WishList', 'WishList'), ('Work', 'Work'), ('All', 'All'), ('Default', 'Default')], max_length=250),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task_list',
            field=models.CharField(choices=[('Shopping', 'Shopping'), ('Personal', 'Personal'), ('WishList', 'WishList'), ('Work', 'Work'), ('All', 'All'), ('Default', 'Default')], max_length=250),
        ),
    ]
