# Generated by Django 3.2.7 on 2021-09-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_task_task_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_list',
            field=models.CharField(choices=[('Shopping', 'Shopping'), ('Personal', 'Personal'), ('WishList', 'WishList'), ('Work', 'Work'), ('All', 'All List')], max_length=250),
        ),
    ]
